spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:master
          driver-class-name: org.h2.Driver
          schema: classpath*:db/schema.sql
        db1:
          username: sa
          password: ""
          url: jdbc:h2:mem:db1
          driver-class-name: org.h2.Driver
          schema: classpath*:db/schema.sql
          data: classpath*:db/db1.sql
        db2:
          username: sa
          password: ""
          url: jdbc:h2:mem:db2
          driver-class-name: org.h2.Driver
          schema: classpath*:db/schema.sql
          data: classpath*:db/db1.sql
        db3:
          username: sa
          password: ""
          url: jdbc:h2:mem:db3
          driver-class-name: org.h2.Driver
          schema: classpath*:db/schema.sql
          data: classpath*:db/db1.sql
logging:
  level:
    com.baomidou: debug
    org.springframework.context.support: off
shiro:
  loginUrl: /login
  successUrl: /index