spring:
  datasource:
    dynamic:
      hikari:
        min-idle: 5
        max-pool-size: 8
      druid:
        min-idle: 5
        max-active: 8
      beecp:
        initial-size: 5
        max-active: 8
      dbcp2:
        min-idle: 5
        max-idle: 8
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: org.h2.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            min-idle: 6
        db1:
          username: sa
          password: ""
          url: jdbc:h2:mem:test1
          driver-class-name: org.h2.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            min-idle: 6
        db2:
          username: sa
          password: ""
          url: jdbc:h2:mem:test2
          driver-class-name: org.h2.Driver
          type: cn.beecp.BeeDataSource
          beecp:
            initial-size: 6
        db3:
          username: sa
          password: ""
          url: jdbc:h2:mem:test3
          driver-class-name: org.h2.Driver
          type: org.apache.commons.dbcp2.BasicDataSource
          dbcp2:
            min-idle: 6

logging:
  level:
    com.baomidou: debug