spring:
  profiles:
    active: postgresql
seata:
  enabled: true
  application-id: applicationName
  tx-service-group: my_test_tx_group
  #一定要是false
  enable-auto-data-source-proxy: false
  service:
    vgroup-mapping:
      #key与上面的tx-service-group的值对应
      my_test_tx_group: default
    grouplist:
      #seata-server地址仅file注册中心需要
      default: 110.40.253.205:8091
  config:
    type: file
  registry:
    type: file
logging:
  level:
    org.springframework.jdbc.datasource: debug
    com.baomidou.dynamic: debug