spring:
  application:
    name: dynamic
  datasource:
    dynamic:
      primary: order
      strict: true
      seata: true    #开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata-mode: AT #支持XA及AT模式,默认AT
      datasource:
        order:
          username: root
          password: 123456
          url: jdbc:mysql://110.40.253.205:3306/seata_order
          hikari:
          init:
            schema: classpath:db/mysql/schema-order.sql
        account:
          username: root
          password: 123456
          url: jdbc:mysql://110.40.253.205:3306/seata_account
          hikari:
          init:
            schema: classpath:db/mysql/schema-account.sql
        product:
          username: root
          password: 123456
          url: jdbc:mysql://110.40.253.205:3306/seata_product
          init:
            schema: classpath:db/mysql/schema-product.sql
        test:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL
          driver-class-name: org.h2.Driver
          seata: false #这个数据源不需要seata