spring:
  application:
    name: dynamic
  datasource:
    dynamic:
      primary: order
      strict: true
      seata: true    #开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata-mode: AT #支持XA及AT模式,默认AT
      datasource:
        order:
          username: postgres
          password: nknUPjQsY2uz6WST
          url: jdbc:postgresql://110.40.253.205:3306/seata
          hikari:
            schema: seata_order
          init:
            schema: classpath:db/schema-order.sql
        account:
          username: postgres
          password: nknUPjQsY2uz6WST
          url: jdbc:postgresql://110.40.253.205:3306/seata
          hikari:
            schema: seata_account
          init:
            schema: classpath:db/schema-account.sql
        product:
          username: postgres
          password: nknUPjQsY2uz6WST
          url: jdbc:postgresql://110.40.253.205:3306/seata
          hikari:
            schema: seata_product
          init:
            schema: classpath:db/schema-product.sql
        test:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL
          driver-class-name: org.h2.Driver
          seata: false #这个数据源不需要seata