spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL
          driver-class-name: org.h2.Driver
          init:
            schema: db/schema.sql
        slave_1:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL
          driver-class-name: org.h2.Driver
        slave_2:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL
          driver-class-name: org.h2.Driver
logging:
  level:
    root: info