spring:
  datasource:
    dynamic:
      primary: order
      datasource:
        order:
          username: root
          password: 123456
          url: jdbc:mysql://110.40.253.205:3306/local_order
          init:
            schema: classpath:db/schema-order.sql
        account:
          username: root
          password: 123456
          url: jdbc:mysql://110.40.253.205:3306/local_account
          init:
            schema: classpath:db/schema-account.sql
        product:
          username: root
          password: 123456
          url: jdbc:mysql://110.40.253.205:3306/local_product
          init:
            schema: classpath:db/schema-product.sql
logging:
  level:
    com.baomidou: debug
