spring:
  datasource:
    dynamic:
      primary: order
      datasource:
        order:
          username: postgres
          password: nknUPjQsY2uz6WST
          url: jdbc:postgresql://110.40.253.205:5432/local
          hikari:
            schema: local_order
          init:
            schema: classpath:db/postgresql/schema-order.sql
        account:
          username: postgres
          password: nknUPjQsY2uz6WST
          url: jdbc:postgresql://110.40.253.205:5432/local
          hikari:
            schema: local_account
          init:
            schema: classpath:db/postgresql/schema-account.sql
        product:
          username: postgres
          password: nknUPjQsY2uz6WST
          url: jdbc:postgresql://110.40.253.205:5432/local
          hikari:
            schema: local_product
          init:
            schema: classpath:db/postgresql/schema-product.sql
logging:
  level:
    com.baomidou: debug